### ISSUE TITLE
Update to latest version of Espresso and Mockito?

### ISSUE THREAD

**Issue by OleksandrKucherenko** [nenick/android-gradle-template#20]
Hi,

can you update the template for latest community achievements, like: Espresso v2.0, Mockito v2.0?

**Comment by nenick** [comment]
Hey, first thanks for your interest on this project.

Current i spent my time in upgrading the tool setup to support the android studio release version. I'm close to finish this task for both ways to support robolectric.

A co worker will start working on the task to migrate our espresso tests. First reading shows that it contains some api changes and improvements. I plan to wait until he is ready to use his knowledge.

But that should not stop you to create a PR ;)

**Comment by OleksandrKucherenko** [comment]
check my gradle scripts from https://github.com/OleksandrKucherenko/meter
yesterday I commit one interesting fix that allows to run mostly all libs together... MultiDex mode is now a "must have" feature for robolectric enabled APKs.

**Comment by nenick** [comment]
I'm switched to the latest version of espresso (2.2) and mockito (2.0.2-beta) now at the https://github.com/nenick/android-gradle-template/tree/rewrite branch.
