### ISSUE TITLE
Voting: Which is your favourite way to support robolectric?

### ISSUE THREAD

**Issue by nenick** [nenick/android-gradle-template#21]
I'm very thankful that the [novoda](https://github.com/novoda/gradle-android-test-plugin) team created a great plugin to support robolectric. I used this plugin for about one year now. The main advantage was the good support for robolectric + espresso where other plugins had some issues. But I disliked that there was not much support. It's looked like they dropped the support. But since short time they are much more active.

The plugin from [JCAndKSolutions](https://github.com/JCAndKSolutions/android-unit-test) has the same support like the novoda plugin, but much better integration with android studio when you install the android studio plugin.

Now i think about to drop the novoda example. Would someone dislike this decision? Please tell me also short why.

**Comment by senkir** [comment]
https://github.com/robolectric/robolectric-gradle-plugin is probably the preferred solution at this point, as it's being updated by the robolectric team.

**Comment by nenick** [comment]
it should be the best solution. it will never be a solution for me until we have a workaround following issues.

1. with that plugin we have some issues when we combined robolectric and espresso which is tracked here https://github.com/robolectric/robolectric-gradle-plugin/issues/17
2. it is hard to get robolectric tests running inside android studio, documented at https://github.com/robolectric/deckard-gradle

**Comment by JamesGoodwin** [comment]
My problem with robolectric-gradle-plugin is that it uses androidTest sourceset, preventing a clean separation between unit and functional tests (e.g. Espresso). This is a complete deal-breaker for me as functional tests can be very useful for testing parts of the app that would be overly complex using Robolectric.

My preferred way of using Robolectric is having unit-tests in a separate gradle module using the standard java plugin (allowing functional tests and unit tests to work).

**Comment by nenick** [comment]
Looks like we need no plugins anymore. With the new experimental unit test feature we can easy use robolectric. See the example https://github.com/nenick/AndroidStudioAndRobolectric or read a step by step guide http://nenick-android.blogspot.de/2015/02/android-studio-110-beta-4-and.html

**Comment by nenick** [comment]
It is possible to use robolectric without extra plugins but having the possibility to use separated test modules is still essential for me. Another advantage I have all sources anytime in Android Studio instead of switching between unit and android tests.

jcandksolution robolectric plugin is now deprecated and replaced by native unit test support.

So I switched this template back to his original root.
